version: '4.34'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:?error}
      - POSTGRES_USER=${DB_USER:?error}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?error}
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db:${DB_PORT:-5432}
    ports:
      - ${ADMINER_PORT:-8080}:${ADMINER_PORT:-8080}